/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as StringsRouteImport } from './routes/strings'
import { Route as SortingRouteImport } from './routes/sorting'
import { Route as SearchingRouteImport } from './routes/searching'
import { Route as PathfindingRouteImport } from './routes/pathfinding'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as DpRouteImport } from './routes/dp'
import { Route as IndexRouteImport } from './routes/index'

const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const StringsRoute = StringsRouteImport.update({
  id: '/strings',
  path: '/strings',
  getParentRoute: () => rootRouteImport,
} as any)
const SortingRoute = SortingRouteImport.update({
  id: '/sorting',
  path: '/sorting',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchingRoute = SearchingRouteImport.update({
  id: '/searching',
  path: '/searching',
  getParentRoute: () => rootRouteImport,
} as any)
const PathfindingRoute = PathfindingRouteImport.update({
  id: '/pathfinding',
  path: '/pathfinding',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DpRoute = DpRouteImport.update({
  id: '/dp',
  path: '/dp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dp': typeof DpRoute
  '/graph': typeof GraphRoute
  '/pathfinding': typeof PathfindingRoute
  '/searching': typeof SearchingRoute
  '/sorting': typeof SortingRoute
  '/strings': typeof StringsRoute
  '/tree': typeof TreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dp': typeof DpRoute
  '/graph': typeof GraphRoute
  '/pathfinding': typeof PathfindingRoute
  '/searching': typeof SearchingRoute
  '/sorting': typeof SortingRoute
  '/strings': typeof StringsRoute
  '/tree': typeof TreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dp': typeof DpRoute
  '/graph': typeof GraphRoute
  '/pathfinding': typeof PathfindingRoute
  '/searching': typeof SearchingRoute
  '/sorting': typeof SortingRoute
  '/strings': typeof StringsRoute
  '/tree': typeof TreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dp'
    | '/graph'
    | '/pathfinding'
    | '/searching'
    | '/sorting'
    | '/strings'
    | '/tree'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dp'
    | '/graph'
    | '/pathfinding'
    | '/searching'
    | '/sorting'
    | '/strings'
    | '/tree'
  id:
    | '__root__'
    | '/'
    | '/dp'
    | '/graph'
    | '/pathfinding'
    | '/searching'
    | '/sorting'
    | '/strings'
    | '/tree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DpRoute: typeof DpRoute
  GraphRoute: typeof GraphRoute
  PathfindingRoute: typeof PathfindingRoute
  SearchingRoute: typeof SearchingRoute
  SortingRoute: typeof SortingRoute
  StringsRoute: typeof StringsRoute
  TreeRoute: typeof TreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strings': {
      id: '/strings'
      path: '/strings'
      fullPath: '/strings'
      preLoaderRoute: typeof StringsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorting': {
      id: '/sorting'
      path: '/sorting'
      fullPath: '/sorting'
      preLoaderRoute: typeof SortingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searching': {
      id: '/searching'
      path: '/searching'
      fullPath: '/searching'
      preLoaderRoute: typeof SearchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathfinding': {
      id: '/pathfinding'
      path: '/pathfinding'
      fullPath: '/pathfinding'
      preLoaderRoute: typeof PathfindingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dp': {
      id: '/dp'
      path: '/dp'
      fullPath: '/dp'
      preLoaderRoute: typeof DpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DpRoute: DpRoute,
  GraphRoute: GraphRoute,
  PathfindingRoute: PathfindingRoute,
  SearchingRoute: SearchingRoute,
  SortingRoute: SortingRoute,
  StringsRoute: StringsRoute,
  TreeRoute: TreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
